### ISSUE TITLE
Licensing discussion

### ISSUE THREAD

**Issue by andrerpena** [radiscope/radiscope-web#10]
@danigomez , @JonatanSalas and @thiagodds , I'd like to discuss about licensing.

Here are the things that I insist (I'm not willing to give in):
- It MUST NOT be possible for someone to use this code to be a competitor of Radiscope.com.
- It MAY be possible to fork repo, but the fork should provide attribution, remain open-source, and not be able to change the license, hence de AGPL license proposal.

However, I'm willing to give away the possibility for someone to use this code for their own use, including commercially.

So, the question is:

**Do you want people to be able to use Radiscope for free, including commercially, if they host it themselves?**

What are your thoughts? I'll honor the vote of the majority as long as the 2 points are kept.

**Comment by danigomez** [comment]
mmmm i think that it depends of what service we will offer. 
I mean if we give the possibility to host the app, why will they pay for a subscription??
In the Asana and Runrunit case it seems that they give a User limit per Team for free, and with a buscription it can be unlimited and more features... 
What's your idea @andrerpena ???

**Comment by JonatanSalas** [comment]
Agree with dany about this, it depends on the service and what we expect to win with this application

**Comment by andrerpena** [comment]
Thats OK for me.. I don't mind keeping it AGPL at all, free for non commercial use. 

I just thought that the average user of a task management solution is not on IT so for them it's just easier to use the online version and pay for the subscription. That's what SugarCRM and OroCRM does. 

As far as the services.. I think we should have the exact same business model as Asana, because if they were **\* around, they wouldn't be doing that much money. Haha. So I'd go for limited free users, limited features. I just think we will have to give away more than they do just to penetrate the market. 

You are right. Let's keep it the way it is and we can possibly rethink it down the road. 

Let's rock =)
